version: '3.9'

services:
  broker-service:
    network_mode: "host"
    build:
      context: ./../broker-service
      dockerfile: ./../broker-service/broker.dockerfile
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
  # ui:
  #   network_mode: "host"
  #   build:
  #     context: ./../front-ent
  #     dockerfile: ./../front-end/ui.dockerfile
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   deploy:
  #     mode: replicated
  #     replicas: 1
        